apiVersion: v1
kind: Namespace
metadata:
  name: swus-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swus-server
  namespace: swus-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swus-server
  template:
    metadata:
      labels:
        app: swus-server
    spec:
      containers:
      - name: server
        image: pmatysiaq/swus-server:v1.5.1
        ports:
        - containerPort: 5000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
